services:
  api:
    container_name: api
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - ipfs
    environment:
      - IPFS_HOST=ipfs
      - IPFS_PORT=5001

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src:Z
      - ./frontend/public:/app/public:Z
    depends_on:
      - api

  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - ipfs_data:/data/ipfs

volumes:
  ipfs_data:
